name: "Hushify – Fetch Secret"
description: "Retrieve a one-time secret from hushify.io using a token or URL"
author: "hushify.io"

branding:
  icon: lock
  color: purple

inputs:
  hushify:
    description: "Hushify secret token OR full URL"
    required: true

outputs:
  secret:
    description: "The retrieved secret value"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -euo pipefail

        INPUT="${{ inputs.hushify }}"

        if [[ "$INPUT" =~ ^https?:// ]]; then
          HUSHIFY_URL="$INPUT"
        else
          if [[ ! "$INPUT" =~ ^[A-Za-z0-9_-]{20,}$ ]]; then
            echo "❌ Invalid hushify token format"
            exit 1
          fi
          HUSHIFY_URL="https://www.hushify.io?token=$INPUT"
        fi

        HTTP_CODE=$(curl -sSLo /tmp/hushify_response \
          -w "%{http_code}" \
          -H "User-Agent: hushify-github-action/1.1" \
          "$HUSHIFY_URL" || echo "000")

        if [ -z "$HTTP_CODE" ] || [ "$HTTP_CODE" = "000" ] || [ "$HTTP_CODE" -ne 200 ]; then
          echo "❌ Failed to retrieve secret"
          if [ -n "$HTTP_CODE" ] && [ "$HTTP_CODE" != "000" ]; then
            echo "HTTP status: $HTTP_CODE"
          else
            echo "Network error or invalid response"
          fi
          if [ -f /tmp/hushify_response ]; then
            RESPONSE=$(cat /tmp/hushify_response)
            if [ -n "$RESPONSE" ]; then
              echo "Response: $RESPONSE"
            fi
            rm -f /tmp/hushify_response
          fi
          exit 1
        fi

        SECRET=$(cat /tmp/hushify_response)
        rm -f /tmp/hushify_response

        if [ -z "$SECRET" ]; then
          echo "❌ Secret is empty or already consumed"
          exit 1
        fi

        echo "::add-mask::$SECRET"
        echo "secret=$SECRET" >> "$GITHUB_OUTPUT"
